server:
  port: 9095

spring:
  application:
    name: index12306-aggregation-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.emv:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 139.159.224.143:8848
        namespace: 7abe7a43-cb4e-45f8-ad8c-05e7ee100a9d
  main:
    allow-bean-definition-overriding: true

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVrN+wLx7USg0cD1IPbH7UC4WX8Mh/Wtd8WBycYDyK/5xg5ndpTJ5S4zrWsObxOnq0OVzWno0LxhCAPaH89gBLHab+KSvX85AaJjkWJwf4u92Wtlr7BeC9r2cCqeK6JPQVMt8bRRM19dC7D7ls93tjdXSzUC/QAMarRoS6D5bLn4hHQBN2gMRyDuPv2E/tpXgotMa/gkpY4SuYmzqaK2UPnv7K04eYhZg5IIevWqMveSJeoQQjsqO4aqQWnSOs8XOZ5hHqxUownYqIis0oHA7mcRX2Pm7RtR8staHFbNALk0wvm1Wa0s3NNYOGl6Or33VMLJuflH26TaXWJZyZideQIDAQAB
    app-id: 2021000122600170
    charset: UTF8
    format: json
    notify-url: http://7zibjm.natappfree.cc/api/pay-service/callback/alipay
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCWYjzWdCBUybov6YlC2uwnXSpF+cVGjmM0wh9X6nWW/dllWlNG3MEaIqGihL5FbBjE8n8uXT+97Tcfr0GxMnhboOlJT6D2ZKo37+z0amcmvtwg8xdR5wK/UsslF4LkL6N7ZHlNpacfH/SouNsM8wodGkCv75iL9s0h4CtUTusjZlnjETv4B4ibGE7i6YUPVj/uoteuUax6gmL8j72Gm+Lz9gXzgaj6m9jTY9kXI2IT9YCRClMAMlCTtXN4NQ96QuAQQgSS/swM5VJtSItw/dNC59hsUZUQxGnywAlDr7CcAbRqxAP+SUbbzenxmkZo+j6B1p/qVPpUIppXrAmx5+pxAgMBAAECggEAb8Rreuer79hN7LYhMfMLeOYhOQi9ugaxbNCqAulao/He1Rkgs5X2XrpGb0dBMs94SUgBhi//4+SeB4p1xIDCOzeIqtfnxbhjWleTQMSkDYPkjwic2F5dCF08ZkDnIzjUxCyUi0UGxHc3mv5or2MirSaJ1Ti5o6y2IOs+yNYupIuUMwQEXicCZz6OH1Di3k849LoHhxO4RcJkT6RmS+ZyVsiCleMRk6VMIK3awNInQsbNbb1dVNgLB+4Gzc97t4jowbwPILg7GWUa9JaS4HhUeuoNjW2VpAoxyVBrvLty73S+sFv4c3EdNoTHJEtT42t+wQCCp80gnW0XQwVn9T2e0QKBgQDZJBgov92lFSbx7fppwp/mr0oNzZL5ZHlfpnbQHqzfYxGK1nYeRJJsGqG1A3DyV7glUqvTaoNrJwExeIjAShcpg96tVQv2YMlCXNJMUY023bGQLprO8y4do8UZVu6b5lb6renwaImY6K07JPd3TXfo3zbaKUdyMq8qZP70v9lakwKBgQCxS8kVDtsyI2bgN09BZeMcaA2brxzt2/ndi/9KM3Sq/RWKvf2FrBlHBENv1KS/+ePWoE0+QP6NzMZYLdlgCG78ZQydiiPiASBkRkX64usLl1w0pm9tCBTJCr+KgK2StSn9LKkWjWTwkwUc1FFHqUsILtpdtV11vjD1TDtJ03sVawKBgATQbQyyPErFrkhc21lu7DakGkM2FJUc6if5u9afZ3vIaYIngRTotkpZSM6HlgB5e2awb4jParx8b+VV48pHmj3cY5p6MTq0KKIlBrCUekoGHkKxFdOSxqn3kI4gREgGklUad/5RgwN13Slbh3UIrajnEgNCOQhKIWISPSjV/A6rAoGAbP7sVffWJdLB0iHupYPfxXzqsMVNAaX0zJDel11e4ifI8IywqVcOCyzB0KRnzGXx/eZ61kTauY4ked1l/7XvlVcCFG/yc2TB5yOUrhKG8Y9R7kRLyDnpnVbwPlOxYbniYHTuVqECZyvbPsgAWA/pwtQbBvUSyens60C8SjyrNJUCgYBggcb9Mkc+D6UfIDxpXTrAe8Pe9i0bHTSp/ahPTE6GE/TaAvzSmZLnoNye240G95Qpqs67x23vWf8AtlclI2DU3lTxHTXeYeMoXRFaeYaPHAfkem16V+oIyjg786TkovnGK/kO7lETJMaxidOJNaeSdLyJybXMrqvRfaeWKoSrDA==
    server-url: https://openapi.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aggregation:
  remote-url: http://127.0.0.1:${server.port}

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: index12306_aggregation-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1