server:
  port: 9095

spring:
  application:
    name: index12306-aggregation-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.emv:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 139.159.224.143:8848
        namespace: 7abe7a43-cb4e-45f8-ad8c-05e7ee100a9d
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aggregation:
  remote-url: http://127.0.0.1:${server.port}

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: index12306_aggregation-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1